[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
db_host = db
db_user = odoo
db_password = odoo
admin_passwd = $pbkdf2-sha512$600000$wpgzBuBcC2Gs9d5by7nXOg$R5CR6qsZGiJbhJEpahl05BQKav34AcYVhwA4pKvu.9QHQX0tIAXFm0dy.72Gl5BHeGzkj6YZTV9IIuCd8zp4CQ

